version: '3'
services:
  pubsub-emu:
    build:
      context: .
      dockerfile: Dockerfile.emu
    image: pubsub-emu
    networks:
      judge-sample-network:
        aliases:
          - emu
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: judge-sample
    command: /judge/script/run_local.sh
    environment:
      PROJECT_ID: sample-project
      TOPIC_NAME: sample-topic
      SUBSCRIPTION_NAME: sample-subsc
      PUBSUB_EMULATOR_HOST: emu:8085
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
    networks:
      - judge-sample-network
    depends_on:
      - pubsub-emu

networks:
  judge-sample-network:
