apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-deployment
  labels:
    app: judge-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-template
  template:
    metadata:
      labels:
        app: judge-template
    spec:
      containers:
      - name: judge
        image: ${DOCKER_IMAGE}
        env:
          # Application Config
          - name: PROJECT_ID
            value: ${PROJECT_ID}
          - name: SUBSCRIPTION_NAME
            value: ${SUBSCRIPTION_NAME}
          - name: TOPIC_NAME
            value: ${TOPIC_NAME}
          - name: BQ_DATASET
            value: ${BQ_DATASET}
          - name: BQ_TABLE
            value: ${BQ_TABLE}

          # GCP Credentials config
          - name: GOOGLE_CLOUD_PROJECT
            value: ${PROJECT_ID}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /judge/key.json
