apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-deployment
  labels:
    app: judge-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-template
  template:
    metadata:
      labels:
        app: judge-template
    spec:
      containers:
      - name: judge
        image: ${DOCKER_IMAGE}
        env:
          - name: PROJECT_ID
            value: ${PROJECT_ID}
          - name: SUBSCRIPTION_NAME
            value: ${SUBSCRIPTION_NAME}
          - name: TOPIC_NAME
            value: ${TOPIC_NAME}
